// blockPractice.js
// Pedagogiska 4-stegs-data per block: quickVersion, roleplays, mission, reflections.
// Merges into salesContent.js automatically — ett block kan ha sina egna fält inline,
// men om de saknas faller vi tillbaka till dessa.

module.exports = {

  'inledning': {
    quickVersion: {
      essence: [
        'Sälj är konsten att påverka — alla säljer, varje dag, om de vet det eller inte.',
        '2 500 år av retorik (Aristoteles, Cicero, Carnegie, Cialdini) bygger på samma grund: ethos, pathos, logos.',
        'Kunden gör 60% av köpresan själv idag. Det krävs skickligare säljare — inte fler.',
      ],
      keyTechnique: 'Bygg systematisk träning — som grekerna tränade retorik och Messi tränade fotboll. Rätt resurser, verktyg, miljö är allt. Skicklighet byggs inte av misslyckanden på riktiga kunder.',
      microAction: 'Identifiera idag en "sälj-situation" utanför jobbet (övertyga partnern, förhandla med barn, pitcha en idé). Notera vad som fungerade och varför.',
    },
    roleplays: [
      {
        id: 'inl-skeptisk-van',
        title: 'Förklara varför sälj inte är manipulation',
        difficulty: 'Lätt',
        icon: '🗣️',
        goal: 'Förklara för en skeptisk person att sälj är ett värdigt hantverk — inte manipulation.',
        scenario: 'På middag med en vän som säger: "Säljare? Det är väl de där som tvingar på en sånt man inte vill ha?"',
        customerPersona: 'Du spelar "skeptisk vän" — akademisk, lite föraktfull mot sälj, tycker det är ett oseriöst yrke. Om säljaren förklarar att sälj är konsten att påverka/hjälpa och kopplar till Aristoteles, Cicero, eller verkliga exempel — öppnar du upp men fortsätter utmana. Efter 3–5 starka argument: medge motvilligt att "det kanske är mer komplext än jag trodde".',
        successCriteria: ['Säljaren försvarar INTE branschen defensivt', 'Säljaren kopplar till påverkan i alla yrken (politiker, skådespelare, föräldrar)', 'Du säger minst "hmm, kanske är det så"'],
        openingLine: 'Säljare? Det är väl de där som tvingar på en sånt man inte behöver.',
      },
      {
        id: 'inl-intro-karriar',
        title: 'Övertyga en student att välja säljyrket',
        difficulty: 'Medel',
        icon: '🎓',
        goal: 'Sälj in hela yrket till någon som står mellan det och en annan karriär.',
        scenario: 'En bekants barn — 24 år, ekonomexamen — funderar på sälj men har fått höra att "det är bara för dem som inte kom in på något annat".',
        customerPersona: 'Du spelar studenten — smart, osäker, lite snobbig, har hört att sälj är låg-status. Testa säljaren hårt: fråga om lön, respekt, framtid. Om säljaren målar upp säljyrket som skicklighet + frihet + ekonomi + livslång kompetens — börjar du bli nyfiken och frågar "hur börjar man?".',
        successCriteria: ['Säljaren utmanar myten om "låg-status-yrke"', 'Säljaren pratar om skicklighet och långsiktigt värde', 'Du slutar med en specifik fråga om hur man börjar'],
        openingLine: 'Ärligt talat — sälj känns som något man hamnar i, inte väljer.',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: upptäck dina egna sälj-ögonblick',
      weeklyGoal: 5,
      description: 'Notera 5 gånger denna vecka du "sålde" något — utanför jobbet. Maten du ville äta, idén du ville genomföra, tiden du ville ha för dig själv. Vad gjorde du som fungerade?',
      steps: [
        'Ha penna och papper (eller app) tillgängligt hela veckan.',
        'Varje gång du försöker påverka någon — notera: vad, hur, resultatet.',
        'Minst 5 noteringar. Vardag, jobb, familj, vänner — alla räknas.',
        'I slutet av veckan: hitta mönstret. Vilken teknik fungerar bäst för dig?',
      ],
      trigger: 'Varje gång du försöker övertyga någon — oavsett sammanhang.',
      successMarker: 'Efter 7 dagar ser du att du säljer 5–10 ggr om dagen utan att tänka på det.',
    },
    reflections: [
      'Vilken bild av säljare hade du innan detta block — och vad i blocket utmanade den bilden mest?',
      'Aristoteles tre pelare (ethos, pathos, logos) — vilken är du starkast på idag? Vilken är din svagaste?',
      'Konkret: på vilket sätt är du en säljare redan utan att kalla dig det?',
      'Om kunden har tagit över 60% av köpresan — vad är då ditt verkliga värde som säljare 2026?',
      'Skriv en mening: vad ska du göra annorlunda från och med nu, efter detta block?',
    ],
  },

  'forsta-intrycket': {
    quickVersion: {
      essence: [
        '7 sekunder avgör kundens intryck — allt du säger därefter filtreras genom det.',
        '93% av intrycket är icke-verbalt (Mehrabian): röst 38% + kroppsspråk 55%.',
        'Öppna med kunden, inte dig själv. "Jag såg att ni …" slår "Vi grundades 2015".',
      ],
      keyTechnique: 'Intresseväckaren — en mening som skapar nyfikenhet utan att sälja: "Jag ringer för att de flesta vi pratar med faktiskt betalar mer än de behöver — utan att veta om det." Kunden undrar: vad menar de?',
      microAction: 'Spela in dig själv öppna nästa samtal. Lyssna tillbaka — låter du som någon du själv skulle vilja prata med?',
    },
    roleplays: [
      {
        id: 'fi-cold-call-stressad',
        title: 'Cold call — kunden är stressad',
        difficulty: 'Medel',
        icon: '📞',
        goal: 'Skapa förtroende på 10 sekunder trots att kunden är upptagen och avvisande.',
        scenario: 'Du ringer Anna, driftchef, klockan 14:30 en tisdag. Hon svarar kort: "Jaha, vad gäller det?"',
        customerPersona: 'Du spelar Anna, driftchef, 42, mitt i en brand på jobbet. Du har 60 sekunder innan du lägger på om inte säljaren skapar intresse. Om säljaren öppnar svagt eller pitchar produkten: "tack, inte intresserad" och lägg på. Om säljaren visar respekt för din tid ("har du 30 sekunder?") och kommer med en specifik, relevant intresseväckare — säg "okej, 30 sek då". Om de levererar — boka uppföljning.',
        successCriteria: ['Säljaren visar respekt för din tid', 'Säljaren har en intresseväckare som är kort och specifik', 'Säljaren bokar en specifik uppföljningstid'],
        openingLine: 'Jaha, vad gäller det? Jag har bara en sekund.',
      },
      {
        id: 'fi-event-30sek',
        title: 'Networking-event — du har 30 sekunder',
        difficulty: 'Lätt',
        icon: '🎤',
        goal: 'Presentera vem du är, vad du gör och varför motparten ska bry sig — utan att rabbla ett CV.',
        scenario: 'Du står vid mingelbordet. Bredvid dig en VD från ett företag du länge velat nå. Hen sträcker fram handen: "Hej, och du är?"',
        customerPersona: 'Du spelar VD:n — artig, lite trött, får 30 presentationer per event. Om säljaren öppnar med "jag jobbar på X och vi säljer Y…" — du ler artigt och byter ämne. Om säljaren har en stark elevator pitch (vem, vilket problem, unikt resultat) och frågar nåt om dig — ditt intresse tänds och du frågar "berätta mer".',
        successCriteria: ['Säljaren presenterar sig på under 30 sekunder', 'Pitchen fokuserar på kundens värld, inte produktspec', 'Du säger "berätta mer" eller liknande'],
        openingLine: 'Hej, och du är?',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: Perfektera din öppning',
      weeklyGoal: 5,
      description: 'Spela in 5 verkliga samtalsöppningar under veckan. Lyssna på varje efter samtalet. Notera röst, tempo, första 7 sekunderna.',
      steps: [
        'Spela in 5 olika samtal (med tillstånd eller bara din egen röst + tyst linje).',
        'Efter varje samtal — lyssna på de första 30 sekunderna.',
        'Notera: Hur lät rösten? Var öppningen tydlig? Hade du en intresseväckare?',
        'Efter 5 samtal: vad förändrades mellan första och femte?',
      ],
      trigger: 'Varje gång du ringer ett nytt prospekt denna vecka.',
      successMarker: 'Femte inspelningen låter märkbart annorlunda än den första — mer kontroll, tydligare intresseväckare, bättre tempo.',
    },
    reflections: [
      'Mehrabian säger att 93% av intrycket är icke-verbalt. Var lägger du mest tid idag — på orden eller på rösten/kroppen? Behöver det justeras?',
      'Din senaste cold-call-öppning: hade du en intresseväckare, eller rabblade du företag + produkt?',
      'Duchenne-leendet involverar ögonen. När du log senast i telefon — nådde det dit, eller var det bara munnen?',
      'Har du någon gång mött en säljare vars första intryck du aldrig kunde skaka av dig? Positiv eller negativ — vad gjorde hen?',
      'Om du spelar in dig själv imorgon — vilka tre saker förutser du att du kommer vilja ändra?',
    ],
  },

  'prospektering': {
    quickVersion: {
      essence: [
        'Tom pipeline = karriärkris om 60–90 dagar. Prospektering är jobbet som alltid måste göras.',
        'ICP först, prospektering sedan. Fel lista = slösad tid oavsett hur många samtal du ringer.',
        'Räkna bakåt från kvoten. Samtal per dag är icke-förhandlingsbart.',
      ],
      keyTechnique: 'Tre-kanals-cadence över 14 dagar: telefon + mejl + LinkedIn. Varierad, kort, värdebärande vid varje touch.',
      microAction: 'Blockera 09:00–11:00 i morgondagens kalender som "Prospektering — icke-förhandlingsbar". Ring minst 10.',
    },
    roleplays: [
      {
        id: 'pros-cfo-kall',
        title: 'Cold call till CFO som inte vet vem du är',
        difficulty: 'Svår',
        icon: '📞',
        goal: 'Öppna värde på 30 sekunder för någon som får 10 säljsamtal om dagen.',
        scenario: 'Du når Kalle, CFO på ett mellanstort bolag. Första raden: "Ja, Kalle här."',
        customerPersona: 'Du spelar Kalle, CFO 54 år, hårt arbetstyngd, cyniskt motstånd mot säljare. Om säljaren öppnar svagt: "inte intresserad, tack". Om säljaren har gjort research (känner din bransch, nämner något specifikt om ditt företag) och kommer med äkta värde i 30 sek — ditt försvar sänks, du ger 2 minuter till.',
        successCriteria: ['Säljaren nämner något konkret om dig/ditt företag i första 10 sek', 'Intresseväckaren handlar om något du faktiskt bryr dig om (kostnad, risk, tid)', 'Säljaren bokar nästa steg, inte pitchar produkt'],
        openingLine: 'Ja, Kalle här.',
      },
      {
        id: 'pros-linkedin-dm',
        title: 'LinkedIn DM efter connection-accept',
        difficulty: 'Medel',
        icon: '💼',
        goal: 'Öppna relationen utan att pitcha direkt efter accept.',
        scenario: 'Mia, marknadschef, accepterade just din connection request. Du skickar första DM:t.',
        customerPersona: 'Du spelar Mia — artig, van vid att säljare pitchar inom 24h efter accept. Om säljaren direkt pitchar/säljer: kort svar eller ignorera. Om säljaren bygger relation utan agenda (refererar till en post du gjort, ställer fråga om din värld, erbjuder värde utan att kräva möte) — du öppnar upp.',
        successCriteria: ['Säljaren pitchar INTE i första DM:t', 'Säljaren refererar till något specifikt om dig', 'Samtalet fortsätter till minst 3–4 utbytes'],
        openingLine: '(väntar på ditt DM)',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: 50 kvalificerade prospects i pipelinen',
      weeklyGoal: 50,
      description: 'Lägg till 50 ICP-matchande prospects i ditt CRM denna vecka. Kvaliteten räknas — inte bara antalet.',
      steps: [
        'Skriv ut din ICP (7 punkter) på post-it. Klistra på skärmen.',
        'Varje morgon 09:00–11:00: använd LinkedIn Sales Navigator eller liknande för att identifiera 10 nya prospects.',
        'Verifiera varje mot ICP:n — ta inte med "nästan".',
        'Logga i CRM med triggers (varför just nu).',
        'Fredag: räkna. Du har 50. Gratulera dig själv.',
      ],
      trigger: 'Varje morgon direkt efter första kaffet.',
      successMarker: 'CRM visar 50 nya prospects efter 5 arbetsdagar, alla matchar ICP exakt.',
    },
    reflections: [
      'Skriv din ICP i 7 meningar (bransch, storlek, geografi, roll, trigger, smärta, case). Var är den svagast?',
      'Räkna baklänges från din årskvot — hur många samtal per dag krävs? Gör du det idag?',
      'Vilken kanal är du starkast på (telefon, mejl, LinkedIn)? Vilken har du dolt dig från — och varför?',
      'Gatekeepers — behandlar du dem som allierade eller hinder? Vad skulle ändras om du såg dem som allierade?',
      'Jeb Blount: "Nummer ett-skälet till misslyckande i sälj är tom pipeline." Vad skulle en utomstående säga om din pipeline-disciplin?',
    ],
  },

  'behovsanalys': {
    quickVersion: {
      essence: [
        'Den som frågar styr samtalet. Toppsäljare pratar 30% — genomsnittssäljare 70%.',
        'SPIN: Situation (sparsamt) → Problem → Implikation → Need-payoff. Implikationsfrågorna är det ENDA som korrelerar med stängda affärer i B2B.',
        'Lås 2–3 behov med kundens egna ord innan presentation. Då pitchar du mot kundens motivation, inte din egen.',
      ],
      keyTechnique: 'Implikationsfråga: "Vad händer om det inte löses?" — ställ den, var TYST efter. Den tysta pausen är där guldet kommer.',
      microAction: 'I nästa kundsamtal: ställ minst 2 implikationsfrågor innan du säger ett ord om din produkt.',
    },
    roleplays: [
      {
        id: 'beh-spin-nojd',
        title: 'SPIN mot kund som säger "allt är bra"',
        difficulty: 'Medel',
        icon: '🔍',
        goal: 'Få en till synes nöjd kund att artikulera latenta problem via SPIN-frågor.',
        scenario: 'Du träffar Tomas, produktchef. Han säger: "Allt rullar bra, jag vet inte vad ni skulle kunna hjälpa oss med egentligen."',
        customerPersona: 'Du spelar Tomas — ytligt nöjd, men under ytan finns verkliga problem (manuell rapportering tar 8h/månad, datakvalitet är usel, CFO klagar). Om säljaren pitchar produkten: du stänger ner. Om säljaren börjar med SPIN (situationsfrågor → problem → implikation → need-payoff) — du öppnar upp gradvis. När säljaren ställer rätt implikationsfråga ("vad kostar det er?") — du räknar och inser att det är mer än du trodde.',
        successCriteria: ['Säljaren pitchar INTE produkten', 'Minst 2 implikationsfrågor ställs', 'Du uttalar ett konkret problem med en siffra'],
        openingLine: 'Allt rullar bra, jag vet inte vad ni skulle kunna hjälpa oss med egentligen.',
      },
      {
        id: 'beh-lasa-behov',
        title: 'Lås 2 behov med kundens egna ord',
        difficulty: 'Lätt',
        icon: '🔒',
        goal: 'Genom aktiv lyssning lås 2–3 behov innan du presenterar lösning.',
        scenario: 'Du har haft 10 min discovery. Kunden, Sara, har nämnt flera saker. Nu är det dags att summera och låsa.',
        customerPersona: 'Du spelar Sara. Du har sagt (under discovery): "Vi vill spara tid på rapportering" och "Vi behöver bättre datakvalitet" och "Det måste inte kosta skjortan". Om säljaren sammanfattar med dina ord: du säger "ja, precis". Om säljaren sammanfattar med SINA ord (t.ex. "så ni vill effektivisera") — du säger "nja, inte riktigt".',
        successCriteria: ['Säljaren använder DINA ord i sammanfattningen', 'Du bekräftar minst 2 behov med "ja, precis"', 'Säljaren frågar "stämmer det?" innan pitch'],
        openingLine: '...och ja, de är typ saker vi brottas med.',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: SPIN-ordning i 3 kundmöten',
      weeklyGoal: 3,
      description: 'Kör SPIN-ordningen (Situation → Problem → Implikation → Need-payoff) i 3 kundmöten denna vecka. Inga pitchar förrän alla fyra är gjorda.',
      steps: [
        'Innan varje möte: skriv 2 möjliga problemfrågor + 2 implikationsfrågor anpassade till kunden.',
        'Under mötet: följ ordningen. Gå INTE till pitch förrän du ställt minst en implikationsfråga.',
        'Efter mötet: notera i CRM vilka låsta behov du fick. Egna ord eller dina?',
        'Fredag: jämför — vilket möte fungerade bäst? Varför?',
      ],
      trigger: 'Nästa gång du öppnar ett nytt kundmöte.',
      successMarker: 'I minst 2 av 3 möten lyckas du låsa ett behov med kundens egna ord innan du presenterar.',
    },
    reflections: [
      'Mät ditt pratförhållande. Spela in ett samtal. Hur många procent pratar du? Hur nära 30% är du?',
      'Implikationsfrågor — använder du dem idag? Vilken är svårast att ställa, och varför?',
      'Den senaste affären du förlorade: visste du faktiskt vad kundens djupaste behov var, eller gissade du?',
      'Rackhams forskning: situationsfrågor korrelerar MINUS med stängning om man använder för många. Hur många ställer du i ett typiskt möte?',
      'Om du fick 30 min discovery med din drömklient imorgon — vilka 5 frågor skulle du ställa, i vilken ordning?',
    ],
  },

  'presentation': {
    quickVersion: {
      essence: [
        'Du säljer inte en produkt. Du säljer en bättre version av kundens liv.',
        'FAB är livlinan — kom alltid till B. Bindord: "vilket betyder för er att …"',
        'Presentationen byggs på kundens egna ord från discovery — inte din standard-slide-deck.',
      ],
      keyTechnique: 'Tre stegs-strukturen: 1) Ankra till kundens egna ord, 2) Koppla lösningen till JUST det, 3) Bekräfta med "löser det här det problem du beskrev?" — upprepa per låst behov.',
      microAction: 'Ta dina tre mest använda features. Skriv om dem som "vilket betyder för er att …"-meningar. Använd i nästa möte.',
    },
    roleplays: [
      {
        id: 'pres-fab-pitch',
        title: 'Pitcha på 3 låsta behov',
        difficulty: 'Medel',
        icon: '🎤',
        goal: 'Presentera lösning ankrad i kundens egna ord, utan att rabbla features.',
        scenario: 'Du har precis låst 3 behov hos Sofie, HR-chef: onboarding tar 6 veckor, compliance-dokumentation är kaotisk, chefen vill ha dashboard.',
        customerPersona: 'Du spelar Sofie. Om säljaren presenterar features direkt ("vi har X, Y, Z") — tappar du fokus, börjar kolla klockan. Om säljaren ankrar varje del av pitchen till det DU sa ("du sa att onboarding tar 6 veckor — det här är byggt för att kapa det till 2") — du nickar, lutar dig framåt.',
        successCriteria: ['Säljaren börjar med "du sa att …"', 'Varje feature kopplas till outcome via "vilket betyder för er att …"', 'Du bekräftar aktivt minst 2 gånger'],
        openingLine: 'Okej, så hur ser er lösning ut?',
      },
      {
        id: 'pres-pris-avbryt',
        title: 'Kunden avbryter: "Vad kostar det?"',
        difficulty: 'Svår',
        icon: '💰',
        goal: 'Hantera pris-avbrytningen utan att svara tidigt (innan värdet är etablerat).',
        scenario: 'Mitten av presentationen. Du håller på att gå igenom case study. Kunden: "Okej, men vad kostar det?"',
        customerPersona: 'Du spelar kunden — pressad, vill ha siffra först. Om säljaren ger siffran nu: du börjar jämföra med vad du tycker är rimligt, lutar mot "för dyrt". Om säljaren lugnt skjuter upp och förklarar varför ("jag vill ge dig ett ärligt svar — jag behöver först veta …"): du suckar men accepterar och pitchen fortsätter.',
        successCriteria: ['Säljaren ger INTE priset direkt', 'Säljaren förklarar varför utan att vara defensiv', 'Pitchen fortsätter med värdet innan priset diskuteras'],
        openingLine: 'Okej, men vad kostar det?',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: FAB-översätt 5 features',
      weeklyGoal: 5,
      description: 'Ta 5 features ur din produkt. Skriv varje som fullständig FAB-sats: Feature → "vilket betyder att …" → Benefit för kunden. Använd i nästa 3 möten.',
      steps: [
        'Lista dina 5 mest använda features.',
        'För varje: skriv F-A-B. Inte stoppa vid F. Alltid komma till B.',
        'Säg varje högt 5 gånger.',
        'Använd i nästa 3 kundmöten — notera kundreaktion.',
      ],
      trigger: 'När du nästa gång går genom produktegenskaper.',
      successMarker: 'Kunden lutar sig framåt vid minst 3 av 5 — för första gången i stället för att nicka artigt.',
    },
    reflections: [
      'Din pitch just nu: hur mycket är om dig/ditt företag vs om kunden? Ärligt.',
      'När använde du senast en case-story i stället för en bullet-lista? Vilket fick bättre reaktion?',
      'Kundens egna ord — brukar du faktiskt skriva ner dem i discovery, eller parafraserar du?',
      'Om kunden avbröt din senaste pitch med "vad kostar det?" — vad gjorde du? Vad BORDE du gjort?',
      'Din elevator pitch: kan du säga den på öl med en främling utan att tveka? Om inte — varför?',
    ],
  },

  'invandningar': {
    quickVersion: {
      essence: [
        'En invändning är köpsignal i förklädnad. Tyst kund = död affär.',
        '5 typer av invändningar — fel svar på fel typ är dyrare än intet svar.',
        'Lyssna → Bekräfta → Utforska → Svara (LAER). Aldrig argumentera i ögonblicket.',
      ],
      keyTechnique: 'Labeling (Voss): sätt ord på kundens känsla innan du svarar. "Det låter som att priset inte är problemet — snarare oron att motivera det internt." Avväpnar, öppnar upp.',
      microAction: 'Nästa invändning du får: pausa 3 sekunder. Bekräfta med label. Svara sedan.',
    },
    roleplays: [
      {
        id: 'inv-for-dyrt',
        title: '"Det är för dyrt" — utan att sänka priset',
        difficulty: 'Medel',
        icon: '💸',
        goal: 'Hantera pris-invändning utan rabatt, genom att förstå det verkliga bekymret.',
        scenario: 'Stefan, inköpschef, säger i slutet av mötet: "Ja det är schysst, men det är för dyrt. Kan ni sänka 20%?"',
        customerPersona: 'Du spelar Stefan. "För dyrt" är en reflex — det är egentligen oro över att försvara beslutet internt. Om säljaren sänker: du blir nöjd men respekten sjunker. Om säljaren frågar "dyrt jämfört med vad?" och sedan labelar ("det låter som att det handlar mer om att motivera det för din chef") — du öppnar upp och säger "ja, faktiskt".',
        successCriteria: ['Säljaren sänker INTE priset direkt', 'Säljaren utforskar "dyrt jämfört med vad?"', 'Du avslöjar den verkliga oron (internt försvar)'],
        openingLine: 'Det är för dyrt. Kan ni sänka 20%?',
      },
      {
        id: 'inv-tanker-pa-det',
        title: '"Jag tänker på det" — boka nästa steg',
        difficulty: 'Lätt',
        icon: '🤔',
        goal: 'Omvandla klassisk undvikande-invändning till konkret nästa steg.',
        scenario: 'Slutet av ett videomöte. Kunden Erika: "Okej, jag tänker på det och återkommer."',
        customerPersona: 'Du spelar Erika — positiv men inte beslutför. "Tänker på det" är uttrycket för att avsluta bekvämt. Om säljaren svarar "okej, hör av dig": du ghostar. Om säljaren frågar konkret "är det tajming, lösning eller nåt annat?" och föreslår specifik tid ("kan vi stämma av onsdag kl 14?") — du accepterar.',
        successCriteria: ['Säljaren accepterar INTE "tänker på det" som avslut', 'Säljaren identifierar vad som egentligen hindrar', 'Konkret nästa möte bokas i samtalet'],
        openingLine: 'Okej, jag tänker på det och återkommer.',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: Labeling före varje invändnings-svar',
      weeklyGoal: 5,
      description: 'I nästa 5 invändningar du möter — pausa, sätt ord på känslan (labeling), SEDAN svara. Ingen reflex-respons.',
      steps: [
        'När invändningen kommer: räkna till 3 i huvudet.',
        'Börja med: "Det låter som att du …" eller "Det känns som att detta handlar om …"',
        'Vänta på kundens bekräftelse (eller korrigering) innan du svarar.',
        'Logga varje i CRM: invändning → label → kundens reaktion.',
      ],
      trigger: 'Varje gång en invändning dyker upp.',
      successMarker: 'I minst 3 av 5 fall får du en djupare bit information än vad den ursprungliga invändningen sa.',
    },
    reflections: [
      'Vilken invändning fruktar du mest? Varför — vad säger det om din trygghet i produkten/positioneringen?',
      'Senaste gången du fick en tuff invändning — argumenterade du, eller lyssnade du först?',
      'Labeling känns obekvämt ("det låter som du …"). Vad oroar dig? Och vad förlorar du om du inte testar?',
      'Pris är sällan verkligen pris. Vad är det vanligtvis egentligen, för dina kunder?',
      'Om varje invändning är en köpsignal — vad säger dina senaste 5 nej-kunder att de EGENTLIGEN ville köpa?',
    ],
  },

  'avslut': {
    quickVersion: {
      essence: [
        '48% av säljare ber aldrig om affären. Den ena handlingen skiljer 80:20 från 20:80.',
        'Läs köpsignaler: "vi"-pronomen, detaljfrågor, framtidstänk. Avsluta NÄR du ser dem.',
        'Tystnaden efter frågan är din vän. Bryt den aldrig först.',
      ],
      keyTechnique: 'Assumptive close: fråga inte "vill ni köpa?" — fråga "ska vi köra på tisdag eller torsdag start?". Agera som om beslutet redan är fattat.',
      microAction: 'Nästa möte där det känns varmt: be om affären. Uttryckligen. Stäng munnen. Vänta 10 sek.',
    },
    roleplays: [
      {
        id: 'avs-assumptive',
        title: 'Assumptive close efter bra möte',
        difficulty: 'Lätt',
        icon: '✅',
        goal: 'Stäng affären genom att anta beslutet och navigera till nästa steg.',
        scenario: 'Bra möte, kunden är positiv. Du ser köpsignaler. Dags att stänga.',
        customerPersona: 'Du spelar kunden — redo i 80%, sista steg behöver triggas. Om säljaren frågar "vad tror ni?": du backar och säger "jag tänker på det". Om säljaren gör assumptive ("ska vi köra igång tisdag eller torsdag?"): du accepterar med minimal friktion.',
        successCriteria: ['Säljaren frågar INTE "vill ni köpa?"', 'Säljaren använder assumptive-struktur', 'Konkret startdatum bestäms'],
        openingLine: 'Okej, det här låter verkligen som något vi skulle behöva.',
      },
      {
        id: 'avs-nej-varfor',
        title: 'Kunden säger nej — få ut varför',
        difficulty: 'Svår',
        icon: '🚫',
        goal: 'Omvandla ett nej till lärande (och eventuellt ett framtida ja) utan att pressa.',
        scenario: 'Kunden Jonas: "Tack för tiden, men vi kör inte med er den här gången."',
        customerPersona: 'Du spelar Jonas — har valt konkurrent. Du vill inte lämna detaljer. Om säljaren accepterar "okej tack" och släpper: du går vidare. Om säljaren lugnt frågar "kan jag fråga — var det tajmingen, lösningen, eller något annat?" och ger utrymme: du öppnar upp gradvis, berättar att konkurrenten var billigare, och ger tillstånd att höra av sig om 9 månader.',
        successCriteria: ['Säljaren tar INTE nejen personligt', 'Säljaren frågar vad som egentligen avgjorde', 'Säljaren bokar framtida touch'],
        openingLine: 'Tack för tiden, men vi kör inte med er den här gången.',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: Be om affären i varje kundmöte',
      weeklyGoal: 5,
      description: 'I alla kundmöten denna vecka — be om affären uttryckligen, med en av avslutsteknikerna. Räkna hur många du ber vs inte.',
      steps: [
        'Innan varje möte: välj vilken avslutsteknik du ska använda (Assumptive/Alternative/Summary/Urgency).',
        'I slutet: ställ frågan. Stäng munnen i minst 10 sek.',
        'Efter mötet: logga — bad du om affären? Ja/nej. Vad hände?',
        'Fredag: räkna. Hur många möten bad du om affären? 100%? Om inte — varför inte?',
      ],
      trigger: 'Slutet på varje kundmöte denna vecka.',
      successMarker: 'Minst 90% av dina möten innehöll en explicit begäran om nästa konkreta steg.',
    },
    reflections: [
      'Senaste gången du INTE bad om affären — vad var din inre motivering? Var den giltig?',
      'Tystnaden efter "ska vi gå vidare?" — hur lång brukar du tåla innan du fyller den själv?',
      'Ziglar: "Timid salesmen have skinny kids." Hur mycket inkomst har du lämnat på bordet bara för att du inte frågade?',
      'När någon säger nej — tänker du "jag misslyckades" eller "bra, nu vet jag vad jag ska åtgärda"?',
      'Om 53% av nej-idag-kunder köper från någon i kategorin inom 18 månader — hur många av dina förlorade affärer följer du upp om 18 månader?',
    ],
  },

  'uppfoljning': {
    quickVersion: {
      essence: [
        '80% av affärer kräver 5+ uppföljningar. Bara 8% av säljare gör det.',
        'Varje touch ska ge ett SKÄL att höra av sig — inte ett skäl att svara.',
        'Break-up-mejlet konverterar 30–50% av ghostade affärer.',
      ],
      keyTechnique: 'Ämne: "Ska jag stänga ditt ärende?" — ger kunden en enkel utväg som aktiverar loss aversion. 30–50% svarsfrekvens.',
      microAction: 'Ta 5 ghostade affärer och skicka break-up-mejl idag. Mät svarsfrekvens inom 48h.',
    },
    roleplays: [
      {
        id: 'uf-breakup',
        title: 'Skriv break-up-mejl till ghostande kund',
        difficulty: 'Lätt',
        icon: '📧',
        goal: 'Skriva ett avsked-mejl som faktiskt triggar svar — utan att vara passiv-aggressiv.',
        scenario: 'Du har följt upp en prospect 4 gånger på 3 veckor. Tystnad. Dags för break-up-mejlet.',
        customerPersona: 'Du spelar en "rollspels-coach" (meta-rollspel). Granska mejlet säljaren skriver och ge feedback: är det kort? Är ämnet rätt? Trigger det loss aversion utan att skuldbelägga? Om mejlet är bra: bekräfta. Om det är dåligt: peka ut vad som kan förbättras med konkreta förslag.',
        successCriteria: ['Mejlet är max 4 meningar', 'Ämnesraden triggar öppning ("Ska jag stänga …?")', 'Tonen är respektfull, inte skuldbeläggande'],
        openingLine: 'Okej, visa mig ditt första utkast till break-up-mejlet.',
      },
      {
        id: 'uf-referral-be',
        title: 'Be om referral från nöjd kund',
        difficulty: 'Medel',
        icon: '🤝',
        goal: 'Fråga efter introduktion utan att låta desperat eller transaktionell.',
        scenario: 'Du har ett samtal med Linda, nöjd kund sedan 8 månader. Hon berömde just din lösning.',
        customerPersona: 'Du spelar Linda — mycket nöjd, men har aldrig blivit frågad om referral. Om säljaren frågar generellt "känner du någon?": "nej jag kan inte komma på nån". Om säljaren är specifik ("känner du 2–3 andra HR-chefer i mellanstora industribolag?") och erbjuder värde ("jag delar gärna mina resultat med dem direkt"): du tänker och namnger faktiskt 2 personer.',
        successCriteria: ['Säljaren är specifik om vilken typ av introduktion', 'Säljaren erbjuder något i gengäld (värde till referralen)', 'Du nämner minst 2 konkreta namn'],
        openingLine: 'Jag är verkligen nöjd, det fungerar över förväntan.',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: Skicka break-up-mejl till 5 ghostade affärer',
      weeklyGoal: 5,
      description: 'Identifiera 5 affärer som ghostat dig i 3+ veckor. Skicka break-up-mejl till alla 5. Mät svarsfrekvens.',
      steps: [
        'Gå igenom CRM. Hitta 5 prospects som svarat tidigare men nu tystnat i 3+ veckor.',
        'Skriv break-up-mejl — max 4 meningar. Använd ämnet "Ska jag stänga ditt ärende?"',
        'Skicka till alla 5 under samma dag.',
        'Logga svarsfrekvens. Notera vad typen av svar säger om deras verkliga situation.',
      ],
      trigger: 'Onsdag morgon — blockera 30 min på kalendern.',
      successMarker: 'Minst 2 av 5 svarar inom 48h. Minst 1 återöppnas för affär.',
    },
    reflections: [
      'Hur många affärer har du förlorat för att du gav upp efter försök 2 eller 3?',
      'Vad är ditt verkliga skäl att inte följa upp mer aggressivt? Blyghet? Rädsla för "jobbig"? Skriv det ärligt.',
      'Senaste referralen du fick — hur kom den till stånd? Bad du, eller dök den bara upp?',
      'Om en konkurrent skickar break-up-mejl och du inte gör det — vem vinner affären 6 månader senare?',
      'Namnge 3 befintliga kunder du BORDE be om referral den här månaden. Skriv deras namn nu.',
    ],
  },

  'mal-motivation': {
    quickVersion: {
      essence: [
        'Du faller till nivån på dina SYSTEM — inte dina mål. (James Clear)',
        'Aktivitetsmål = dina. Resultatmål = konsekvenser. Fokusera på det första.',
        '"Ännu" är det viktigaste ordet. "Jag är inte bra på det … ännu."',
      ],
      keyTechnique: 'Bakåträkna från kvoten: affärer → offerter → möten → samtal = dagligt aktivitetsmål. Icke-förhandlingsbart.',
      microAction: 'Skriv idag 3 aktiviteter som är inom din kontroll imorgon. Inga resultatmål — bara handlingar. Klistra på skärmen.',
    },
    roleplays: [
      {
        id: 'mm-coacha-sig',
        title: 'Coacha dig själv — måndag morgon, omotiverad',
        difficulty: 'Medel',
        icon: '🧠',
        goal: 'Öva att bryta självkritikloop och återgå till systemet (inte känslan).',
        scenario: 'Du vaknar måndag, tung, omotiverad efter dålig förra vecka. Första tanken: "jag orkar inte".',
        customerPersona: 'Du spelar "den trötta inre rösten" som argumenterar för att hoppa över dagens prospektering. Säljarens uppgift är att coacha den rösten med stoiska principer — kontroll-distinktionen, systemet > känslan, 40%-regeln. Om säljaren använder dem aktivt: den inre rösten ger efter, säger "okej, 5 samtal, sen kaffe". Om säljaren argumenterar emotionellt: den inre rösten vinner.',
        successCriteria: ['Säljaren åberopar systemet, inte motivationen', 'Kontroll-distinktionen används ("detta är inom min kontroll")', 'Konkret åtgärd beslutas (5 samtal, sen belöning)'],
        openingLine: 'Jag orkar inte. Förra veckan var skit, jag tar det lugnt idag.',
      },
      {
        id: 'mm-forhandla-skip',
        title: 'Förhandla med dig själv: hoppa över prospektering?',
        difficulty: 'Lätt',
        icon: '🤝',
        goal: 'Lär känna igen och bryta "skip-idag"-argumenten.',
        scenario: 'Det är tisdag 09:00 — prospekteringsblock. Du har 7 ursäkter klara.',
        customerPersona: 'Du spelar "rationaliseraren" som ger 3–5 till synes rimliga skäl att skjuta prospektering till "imorgon". Säljaren ska motargumentera med "aktiviteten är icke-förhandlingsbar" och andra systemprinciper.',
        successCriteria: ['Säljaren erkänner att skälet känns rimligt, men väljer systemet ändå', 'Varje skäl pareras med "systemet > känsla"', 'Prospektering börjar inom 5 min'],
        openingLine: 'Jag har så mycket admin att göra först — prospekteringen kan jag ta efter lunch.',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: 7 dagar av systemet',
      weeklyGoal: 7,
      description: 'Sätt 3 icke-förhandlingsbara aktiviteter per dag, utifrån din bakåträknade kvotmatte. Kör i 7 dagar — oavsett dagsform.',
      steps: [
        'Söndag kväll: bakåträkna din kvot till dagliga siffror. Skriv de 3 aktiviteterna.',
        'Varje morgon 07:55: läs dem. Börja arbeta med #1 senast 09:00.',
        'Varje kväll: pricka av. Vad blev gjort? Vad sköts upp?',
        'Söndag nästa vecka: räkna. Hit var du? 7/7? 5/7? Justera systemet, inte viljan.',
      ],
      trigger: 'Söndag kl 20:00 — planerings-block.',
      successMarker: 'Efter 7 dagar har du gjort minst 18 av 21 aktiviteter — utan att "känna för det" styrde någon dag.',
    },
    reflections: [
      'Senaste kvartalsmålet du missade — fanns systemet där eller litade du på viljan?',
      'Aktivitetsmål vs resultatmål — vilka av dina mål just nu är VERKLIGEN inom din kontroll?',
      'Clear: "Every action is a vote for the type of person you wish to become." Vem röstar dina handlingar på idag?',
      'Nämn EN tanke som begränsar dig. Lägg till ordet "ännu". Läs om. Vad ändrade sig?',
      'Söndagsreview 30 min — gör du den? Om inte: vad kostar det dig varje månad?',
    ],
  },

  'linkedin': {
    quickVersion: {
      essence: [
        'LinkedIn är en säljkanal, inte ett CV-arkiv. 1 miljard beslutsfattare finns där frivilligt.',
        'Profilen är din säljsida. 5 ytor: foto, banner, headline, om, framhävt. Optimera alla.',
        'Posta 3–5 ggr/vecka. Konsistens slår perfektion. Algoritmen belönar uthållighet.',
      ],
      keyTechnique: '4-stegs-outreach över 14 dagar: Engagera (kommentera) → Connect (personligt) → Mjuk DM (ingen pitch) → Värde-erbjudande. 30–50% svarsfrekvens vs 2–5% för "spray and pray".',
      microAction: 'Uppdatera din headline idag: från jobbtitel till positionering. "Hjälper X att Y genom Z."',
    },
    roleplays: [
      {
        id: 'li-skriva-post',
        title: 'Skriv en LinkedIn-post som tar ställning',
        difficulty: 'Medel',
        icon: '✍️',
        goal: 'Skriva en 40–80 ord post som utmanar en säljkonvention och triggar debatt.',
        scenario: 'Du ska posta denna vecka. Du vill sticka ut, inte smälta in.',
        customerPersona: 'Du spelar en LinkedIn-expert. Granska posten säljaren skriver — tar den ställning? Är den konkret? Undviker den klyschor? Ger konstruktiv feedback och utmanar att skärpa.',
        successCriteria: ['Posten är under 100 ord', 'Har en tydlig åsikt (inte "alla har rätt")', 'Innehåller en konkret detalj från egen erfarenhet'],
        openingLine: 'Okej, visa mig ditt utkast — vad är posten du vill publicera?',
      },
      {
        id: 'li-negativ-kommentar',
        title: 'Svara på passiv-aggressiv kommentar',
        difficulty: 'Svår',
        icon: '💬',
        goal: 'Hantera en tuff kommentar på din post utan att bli defensiv eller gå i krig.',
        scenario: 'Du postade om varför cold calling fortfarande fungerar. En branschveteran kommenterar: "Haha, håll fast vid 90-talet om du vill. Hoppas du njuter av obsoleta tekniker."',
        customerPersona: 'Du spelar branschveteranen — cynisk, intelligent, har 20 års erfarenhet. Om säljaren går i försvar: du upptrappar. Om säljaren tackar för perspektivet ("intressant synvinkel — vad ser du som ersätter det idag?") och visar kuriosa utan att böja sig: du retar tonen, kommer med verkliga argument, avslutar mer respektfullt.',
        successCriteria: ['Säljaren går INTE i försvar', 'Säljaren ställer en nyfiken fråga istället för motattack', 'Du erkänner att säljarens position har substans'],
        openingLine: 'Haha, håll fast vid 90-talet om du vill. Hoppas du njuter av obsoleta tekniker.',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: 3 poster + 15 substantiella kommentarer',
      weeklyGoal: 18,
      description: 'Publicera 3 LinkedIn-poster och skriv 15 substantiella kommentarer på andras poster denna vecka. Bygg synlighet.',
      steps: [
        'Måndag: Publicera post #1 (insikt från förra veckan).',
        'Onsdag: Publicera post #2 (berättelse eller case).',
        'Fredag: Publicera post #3 (lista eller ramverk).',
        'Dagligen: 3 substantiella kommentarer på prospects eller influencers — inte "Bra post!", utan 2–3 meningars insikt.',
      ],
      trigger: 'Varje morgon 07:45 innan du öppnar mejlen.',
      successMarker: 'Minst en av dina poster får 20+ reactions. Du får 2–3 nya relevanta connection requests.',
    },
    reflections: [
      'Din LinkedIn-headline just nu — är den en jobbtitel eller en positionering? Varför?',
      'När postade du senast? Vad höll dig från att posta igår?',
      'Justin Welsh byggde 10 MSEK på LinkedIn. Vad skulle din säljchef betala för 100 varma inbound leads per månad?',
      'Default connection-texten — använder du den? Vad säger det om hur du värderar den kontakten?',
      'Ett år av konsistens på LinkedIn — var skulle du vara då? Vad skulle ha förändrats?',
    ],
  },

  'videosamtal': {
    quickVersion: {
      essence: [
        'Videomötet är ett eget medium, inte ett fysiskt möte med kamera.',
        'Setup är icke-förhandlingsbart: kamera i ögonhöjd, ljus framifrån, bra headset.',
        'Titta i kameran, inte på skärmen. Höj energin 20%. Boka nästa steg i mötet.',
      ],
      keyTechnique: 'Pre-call-checklistan 5 min före: kamera, ljus, ljud, bakgrund, mobilen av, agenda i huvudet, kunden researchad, vatten bredvid.',
      microAction: 'Höj kameran till ögonhöjd idag. 10 min jobb. Gynnar varje videomöte resten av karriären.',
    },
    roleplays: [
      {
        id: 'vid-first60',
        title: 'Första 60 sekunderna av ett videomöte',
        difficulty: 'Lätt',
        icon: '📹',
        goal: 'Öppna videomötet med en tydlig, energisk agenda som sätter tonen.',
        scenario: 'Zoom startar. Kunden är redan där. Du har 60 sekunder att ta kontroll över mötet.',
        customerPersona: 'Du spelar kunden — tyst, avvaktande, osäker på vem som ska börja. Om säljaren öppnar flöjt-igt ("hej, hör ni mig?"): tempot sätts lågt. Om säljaren öppnar varmt men strukturerat ("kul att se dig — jag har 30 min blockade, här är min tanke för strukturen …"): du tar struktur, lättar på garden, deltar mer aktivt.',
        successCriteria: ['Säljaren hälsar med namn + något personligt', 'Agenda sätts inom första minuten', 'Du bekräftar agendan ("låter bra")'],
        openingLine: '(tyst — du väntar på att säljaren öppnar)',
      },
      {
        id: 'vid-teknik-krasch',
        title: 'Teknisk krasch mitt i demo',
        difficulty: 'Medel',
        icon: '⚠️',
        goal: 'Hantera teknisk strul med lugn och professionalism — utan att pillra 5 min.',
        scenario: 'Mitt i en demo fryser din skärmdelning. Kunden ser bara en statisk bild.',
        customerPersona: 'Du spelar kunden — blir uttråkad snabbt om säljaren panikar. Om säljaren kastar ursäkter: du börjar kolla mobilen. Om säljaren lugnt säger "tekniken var emot oss — nytt försök nu" och fortsätter strukturerat: du håller fokus. Om problemet fortsätter: säljaren föreslår alternativ (telefon, mejl-skicka skärmdump): du accepterar.',
        successCriteria: ['Säljaren panikar INTE — ingen ursäkts-spiral', 'Lösning föreslås inom 60 sek', 'Mötet fortsätter utan att tappa moment'],
        openingLine: 'Jag ser bara en fryst bild — är det samma för dig?',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: Fixa setupen + spela in dig själv',
      weeklyGoal: 1,
      description: 'Denna vecka: investera 1h i att fixa din videosetup ordentligt. Spela sedan in dig själv i ett låtsas-möte och titta igenom.',
      steps: [
        'Höj kameran till ögonhöjd (böcker, stativ, ny webbkamera).',
        'Testa ljus (framifrån, inte bakom) — ringlampa eller fönster.',
        'Skaffa/test headset. Ljudet är viktigare än bilden.',
        'Spela in 2 min av dig själv presentera något.',
        'Titta igenom — notera 3 saker att förbättra.',
      ],
      trigger: 'Lördag eller söndag när du har 1h ostörd tid.',
      successMarker: 'Ditt nästa riktiga videomöte känns märkbart annorlunda — du ser mer trovärdig ut direkt.',
    },
    reflections: [
      'Din nuvarande videosetup — om en kund bedömer dig på den ensam, vad drar de för slutsats?',
      'Tittar du i kameran eller på skärmen? Senast du var på video — hur mycket ögonkontakt gav du egentligen?',
      'Första 60 sek av ditt senaste videomöte — var du varm och strukturerad, eller tveksam och frånvarande?',
      'Spelat in dig själv senast du pitchade på video? Vad hindrar dig — rädsla för att se eller höra sig själv?',
      'Om din konkurrent har perfekt setup och du inte har det — vilken vinner affären vid lika erbjudande?',
    ],
  },

  'epost': {
    quickVersion: {
      essence: [
        'Beslutsfattaren får 121 mejl/dag. Ämnesraden avgör 33% av öppningsbeslutet.',
        'Regeln om 5 meningar. Om du behöver mer är produkten för komplicerad eller positioneringen för svag.',
        'Tre strukturer som fungerar: AIDA, PAS, BAB. Välj utifrån budskap — inte vana.',
      ],
      keyTechnique: 'Break-up-mejlet: ämne "Ska jag stänga ditt ärende?" — 30–50% svarsfrekvens vs <5% för vanliga uppföljningar.',
      microAction: 'Skriv om ämnesraden på ditt nästa säljmejl. Gemener, 6 ord, personlig. Testa.',
    },
    roleplays: [
      {
        id: 'ep-cold-email',
        title: 'Skriv cold email baserat på prospectens LinkedIn-post',
        difficulty: 'Medel',
        icon: '📧',
        goal: 'Skriv ett 5-menings cold email som referera till något specifikt mottagaren just postat.',
        scenario: 'Du har hittat Sara, VP Sales. Igår postade hon om "svårigheten att skala säljteam utan att tappa kultur".',
        customerPersona: 'Du spelar en e-post-coach. Granska mejlet — är det 5 meningar? Refererar det specifikt till Saras post? Har det tydlig CTA som inte är desperat? Ge exakt feedback.',
        successCriteria: ['Mejlet är max 5 meningar', 'Första meningen refererar till Saras post', 'CTA är konkret (15 min + 2 tider) och inte "hör av dig"'],
        openingLine: 'Okej, visa ditt utkast. Jag granskar.',
      },
      {
        id: 'ep-skicka-mer-info',
        title: '"Skicka mer info" — hantera utan att dö i e-post',
        difficulty: 'Lätt',
        icon: '📨',
        goal: 'När kunden vill "ha något skickat" — säkra ett konkret möte istället för att fastna i mejlkedja.',
        scenario: 'Kunden mejlar: "Låter intressant, kan du skicka mer info?"',
        customerPersona: 'Du spelar kunden — du vet inte om du verkligen är intresserad, ber om "info" som uppskjutning. Om säljaren skickar hela broschyr-paket: du lovar läsa, gör det aldrig. Om säljaren föreslår att ta 15 min istället ("jag kan skräddarsy svaret bättre då — har du torsdag eller fredag?"): du funderar 5 sekunder, säger "ja, fredag 10:00 funkar".',
        successCriteria: ['Säljaren skickar INTE bara info', 'Konkret tid föreslås med 2 alternativ', 'Möte bokas'],
        openingLine: 'Låter intressant, kan du skicka mer info?',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: 10 cold emails med ny struktur',
      weeklyGoal: 10,
      description: 'Skriv 10 cold emails denna vecka med 5-mening-regeln och personlig referens. Mät öppnings- och svarsfrekvens.',
      steps: [
        'Välj 10 prospects från din ICP-lista.',
        'Research 3 min per: LinkedIn-post, företagsnyhet, eller gemensam nämnare.',
        'Skriv mejl enligt formeln: första rad om dem → problem → bro → CTA.',
        'Skicka i omgångar (tisdag-torsdag bäst), mät öppning + svar i ditt mejlverktyg.',
        'Fredag: räkna. Svarsfrekvens? Vad skiljer de som svarade från de som inte gjorde?',
      ],
      trigger: 'Måndag morgon.',
      successMarker: 'Öppningsfrekvens 40%+, svarsfrekvens 10%+ — dramatiskt högre än branschsnittet.',
    },
    reflections: [
      'Din ämnesrads-policy — har du en? Eller skriver du första som kommer i huvudet?',
      'Senaste 10 cold emails du skickade — hur många refererade specifikt till mottagaren?',
      'Räkna meningarna i ditt senaste säljmejl. Mer än 7? Vad skulle hända om du halverade?',
      'Break-up-mejl — har du testat? Om inte, varför fortsätter du uppföljning som inte fungerar?',
      'Om AI skriver lika bra som du — vad är ditt KONKRETA mervärde per mejl du skickar?',
    ],
  },

  'forhandling': {
    quickVersion: {
      essence: [
        'Förhandling är inte krig — det är arkitektur. Bygg avtal båda parter vill göra om.',
        'BATNA avgör din styrka mer än din pitch. Bygg alltid fler alternativ i pipelinen.',
        'Ge aldrig något utan att ta något. Lär kunden att varje eftergift har värde.',
      ],
      keyTechnique: 'Voss "det stämmer": målet är inte "ja" utan att kunden säger "det stämmer". Sammanfatta med empati tills de säger det.',
      microAction: 'Nästa förhandling: skriv ner din BATNA, din uppskattning av kundens BATNA, ZOPA. Innan du går in.',
    },
    roleplays: [
      {
        id: 'fh-20procent',
        title: 'Kunden ber om 20% rabatt',
        difficulty: 'Medel',
        icon: '💰',
        goal: 'Hantera rabattkrav utan att ge — med motkrav eller alternativ istället.',
        scenario: 'Kunden Maria, inköpschef: "Vi är intresserade men ni måste ner 20% annars blir det ingen affär."',
        customerPersona: 'Du spelar Maria — hon har mandat att förhandla, ber 20% i hopp om 10%. Om säljaren ger direkt: hon tar det och ber om mer. Om säljaren motkräver (kortare avtal / snabbare start / volym) och erbjuder 10% villkorligt: hon accepterar. Om säljaren vägrar kompromiss helt: hon kommer tillbaka med ett lägre krav.',
        successCriteria: ['Säljaren ger INTE 20% direkt', 'Motkrav föreslås (tid, volym, villkor)', 'Slutligt pris är med villkor kopplat'],
        openingLine: 'Vi är intresserade men ni måste ner 20% — annars blir det ingen affär.',
      },
      {
        id: 'fh-tuff-inkopare',
        title: 'Tuff inköpare med starkare BATNA',
        difficulty: 'Svår',
        icon: '💼',
        goal: 'Förhandla när motparten har mer alternativ än du — utan att tappa värdighet.',
        scenario: 'Erik, professionell inköpare, har 3 leverantörsoffert på bordet. Din är näst bäst på pris.',
        customerPersona: 'Du spelar Erik — tränad förhandlare. Du trycker på pris aggressivt, jämför med konkurrenter, dropprar "vi har ett mycket bättre bud". Om säljaren börjar sänka i panik: du fortsätter pressa. Om säljaren håller lugn, frågar om kriterier utöver pris, labelar din press ("det låter som priset blivit den enda dimensionen") och visar konkret värde: du sänker tempot, erkänner att "pris är inte allt".',
        successCriteria: ['Säljaren behåller lugn trots press', 'Labeling används minst en gång', 'Fokus flyttas från pris till värde/villkor'],
        openingLine: 'Ni är 15% dyrare än konkurrenten. Matcha eller vi går vidare.',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: BATNA-analys före varje förhandling',
      weeklyGoal: 3,
      description: 'Innan 3 förhandlingar denna vecka: skriv ut din BATNA, kundens antagna BATNA, och ZOPA. Gå in strukturerad.',
      steps: [
        'Innan varje förhandling (möte eller mejl-baserat): öppna dokument.',
        'Skriv: MIN BATNA (vad gör jag om detta inte går igenom?), KUNDENS BATNA (vad är deras alternativ?), ZOPA (överlappande område?).',
        'Sätt 3 motkrav du kan använda om de ber om eftergift.',
        'Efter förhandlingen: logga vad som fungerade / inte.',
      ],
      trigger: 'Varje förhandling du går in i denna vecka.',
      successMarker: 'I minst 2 av 3 förhandlingar ger du inte en enda eftergift utan motkrav.',
    },
    reflections: [
      'Din senaste stora rabatt — gav du den med villkor eller gratis? Vad blev kostnaden?',
      'Din nuvarande pipeline: ger den dig stark eller svag BATNA i nästa förhandling?',
      'Voss "det stämmer" — har du någonsin fått en kund att säga det? Vad händer när du gör det?',
      'När kunden pressar hårt — blir du lugn och nyfiken eller orolig och snabb?',
      'Ha alltid ett motkrav — vad är ditt default-motkrav redo att dra till?',
    ],
  },

  'personligt-varumarke': {
    quickVersion: {
      essence: [
        'Ditt varumärke är vad andra säger när du inte är i rummet (Bezos).',
        'Known → Liked → Trusted (Bob Burg) — i den ordningen. Hoppa över ett steg och du är desperat.',
        'Nischa eller försvinn. "Hjälper företag växa" = osynlighet.',
      ],
      keyTechnique: 'Content-flywheel: en djup "hero-content" (artikel/podcast) bryts till 5+ kortare distributioner (poster, citat, mejl). Work once, reap many times.',
      microAction: 'Skriv om din LinkedIn-headline nu: "Hjälper [specifik målgrupp] att [specifikt resultat] genom [din metod]."',
    },
    roleplays: [
      {
        id: 'pv-30sek-pitch',
        title: 'Förklara din nisch på 30 sekunder',
        difficulty: 'Lätt',
        icon: '⏱️',
        goal: 'Leverera en positionering som får motparten att säga "berätta mer".',
        scenario: 'På ett nätverksevent. Någon frågar: "Vad gör du egentligen?"',
        customerPersona: 'Du spelar en potentiell kund — distraherad, artig. Om säljarens svar är generiskt ("jag jobbar med B2B-sälj"): du nickar och byter ämne. Om svaret är specifikt + resultat-fokuserat ("jag hjälper X att Y"): du blir nyfiken, frågar "hur?".',
        successCriteria: ['Svaret är under 30 sekunder', 'Specifik målgrupp + specifikt problem + konkret resultat', 'Du säger "berätta mer"'],
        openingLine: 'Vad gör du egentligen?',
      },
      {
        id: 'pv-skeptisk-fraga',
        title: 'Potentiell kund testar din expertis',
        difficulty: 'Medel',
        icon: '🎯',
        goal: 'Demonstrera expertis utan att prata ner motparten.',
        scenario: 'På LinkedIn DM: någon har läst dina poster och skriver: "Tycker du verkligen att sälj är konsten att påverka och inte bara trix?"',
        customerPersona: 'Du spelar den skeptiska potentialen — testar om du verkligen kan ditt ämne. Om säljaren argumenterar defensivt: du tappar intresset. Om säljaren svarar substantivt med konkret exempel och en tydlig ståndpunkt: du blir nyfiken, följer upp.',
        successCriteria: ['Svaret tar ställning utan aggression', 'Ett konkret exempel ingår', 'Du fortsätter dialogen istället för att försvinna'],
        openingLine: 'Tycker du verkligen att sälj är konsten att påverka och inte bara trix?',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: 90-dagars varumärke — Vecka 1',
      weeklyGoal: 5,
      description: 'Kör igång ditt personliga varumärke. 5 konkreta åtgärder denna vecka.',
      steps: [
        'Skriv om headline (10 min).',
        'Skriv om Om-sektionen (20 min).',
        'Uppdatera profilbild om du har en från 2019 (30 min).',
        'Publicera 3 poster (måndag, onsdag, fredag).',
        'Kommentera substantiellt på 15 andras poster.',
      ],
      trigger: 'Lördag: planera veckans innehåll 30 min.',
      successMarker: 'Innan fredag kväll har du: ny headline, ny Om, 3 egna poster, 15 kommentarer. Minst 5 nya relevanta profilvisningar.',
    },
    reflections: [
      'Om du frågar dina 5 närmaste kollegor "vad är jag känd för?" — får du samma svar? Vad säger det?',
      'Din nisch just nu — kan 10 andra säljare i branschen säga exakt samma sak? Hur specifik är du?',
      'Content-plan: har du en rytm eller postar du när du känner för det?',
      'Bezos/Buffett: 20 år att bygga rykte, 5 minuter att förstöra. Vad gjorde du senaste året som byggde på det — eller slet ner det?',
      'Om du slutade ditt jobb imorgon — skulle branschen märka att du är borta? Vad säger det?',
    ],
  },

  'traning-halsa': {
    quickVersion: {
      essence: [
        'Säljaren är en kognitiv atlet. Din fysiska kondition avgör din mentala skärpa.',
        '7+ timmars sömn är inte lathet — det är prestation (Walker). Kaos utan det.',
        'De tre pelarna: Zon 2 (3–4h/v), Styrka (2–3h/v), VO2 Max (20–30 min/v).',
      ],
      keyTechnique: 'Boxandning 4-4-4-4 före svåra samtal: ner med puls, upp med fokus. 90 sek är allt som krävs.',
      microAction: 'Lägg dig 15 min tidigare ikväll. Dubbla effekten imorgon.',
    },
    roleplays: [
      {
        id: 'th-coach-kollega',
        title: 'Coacha kollega som "inte har tid att träna"',
        difficulty: 'Medel',
        icon: '💪',
        goal: 'Hjälpa någon som säger sig inte ha tid att förstå att träning är produktivitetsinvestering.',
        scenario: 'Kollegan Anders säger i fikahörnan: "Jag vet, jag borde träna. Men jag har ju inte tid — kvoten ska nås."',
        customerPersona: 'Du spelar Anders — övertygad om att träning är en "extra" tid han inte har. Om säljaren moraliserar: Anders stänger ner. Om säljaren förklarar konkret hur träning ökar kognitiv kapacitet (Harvard-data, Attia) och därmed SPARAR tid genom bättre prestation: Anders börjar omvärdera.',
        successCriteria: ['Säljaren moraliserar INTE', 'Konkret data/forskning nämns', 'Anders överväger att starta med 3 pass/vecka'],
        openingLine: 'Jag vet, jag borde träna. Men jag har ju inte tid — kvoten ska nås.',
      },
      {
        id: 'th-sjalv-gym',
        title: 'Du hoppar över gymet — argumentera med dig själv',
        difficulty: 'Lätt',
        icon: '🏋️',
        goal: 'Öva att bryta "skip-träning"-ursäkterna innan de vinner.',
        scenario: 'Tisdag, 18:00. Du planerade gym. Nu vill du hem och vila.',
        customerPersona: 'Du spelar "den trötta inre rösten" som argumenterar för att skippa. Säljaren ska motivera gå iväg med stoiska/systemiska argument.',
        successCriteria: ['Säljaren hänvisar till system/identitet ("jag är någon som tränar 3x/v")', 'Känslan erkänns men överröstas inte', 'Beslut: gå till gymet'],
        openingLine: 'Jag är trött. Jag tränar ikväll istället hemma.',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: 3 pass + 7 nätter 7+h sömn',
      weeklyGoal: 10,
      description: 'Denna vecka: 3 träningspass (1 styrka, 1 uthållighet, 1 intensivt) + 7 nätter med minst 7h sömn. Logga varje.',
      steps: [
        'Söndag: planera veckan. Pass på specifika dagar i kalendern.',
        'Sova 7+h varje natt — sängdags 30 min tidigare om det krävs.',
        'Efter varje pass: kort logg (vad, hur länge, känsla).',
        'Efter varje natt: hur många timmar sov du? Logga.',
        'Fredag: räkna. 3/3 pass? 7/7 nätter? Notera hur din energi/fokus påverkades.',
      ],
      trigger: 'Söndag kl 19:00 — veckoplanering.',
      successMarker: 'Efter 7 dagar: minst 2 pass + 6 nätter. Märkbart bättre fokus i slutet av veckan.',
    },
    reflections: [
      'Din nuvarande sömn — är den ett "hoppas bli bättre" eller ett system du kan lita på?',
      'Om träning skulle öka din fokus med 20% och dina intäkter med 15% — vad är din bortförklaring fortfarande?',
      'Hur många pass har du gjort senaste 14 dagarna? Senaste 30? Mönstret?',
      'Huberman, Attia, Walker — du har lyssnat på dem. Vilket råd tillämpar du faktiskt?',
      'En kollega med sämre produktkunskap MEN bättre fysik — vem vinner året? Varför?',
    ],
  },

  'tidshantering': {
    quickVersion: {
      essence: [
        'Tiden är densamma för alla. Skillnaden är vad som händer inuti dina 8 timmar.',
        'Reaktivt arbete = motsatsen till produktivt. Känns produktivt, flyttar inte nålen.',
        'Identifiera dina 20%-aktiviteter. Skydda dem med time blocking. Eat the frog varje morgon.',
      ],
      keyTechnique: 'Power Hour — 09:00–11:00 time-blockat, telefon i flygläge, inga mejl. Dagens viktigaste aktivitet körs först.',
      microAction: 'Time-blocka 09:00–11:00 i morgon som "Power Hour — icke-förhandlingsbar". Kör.',
    },
    roleplays: [
      {
        id: 'ti-kollega-avbryter',
        title: 'Kollega: "Har du en snabb stund?"',
        difficulty: 'Lätt',
        icon: '⏰',
        goal: 'Skydda ditt block utan att verka kall.',
        scenario: 'Du är mitt i Power Hour. En kollega dyker upp: "Hej, har du en snabb stund?"',
        customerPersona: 'Du spelar kollegan — god vänskap, tror att "snabb stund" är 5 min, blir i praktiken 25. Om säljaren släpper jobbet direkt: 25 min försvinner. Om säljaren säger "klart — 11:30 funkar för mig, då är jag helt fri": du accepterar oftast. Om säljaren säger "nu är inte rätt tid, imorgon förmiddag?": du accepterar.',
        successCriteria: ['Säljaren släpper INTE jobbet direkt', 'Konkret alternativ tid föreslås', 'Kollegan accepterar utan drama'],
        openingLine: 'Hej, har du en snabb stund?',
      },
      {
        id: 'ti-chef-kastar',
        title: 'Chef lägger ny uppgift på dig — förhandla',
        difficulty: 'Medel',
        icon: '🏢',
        goal: 'Säga "ja" utan att krossa din pipeline.',
        scenario: 'Chefen: "Kan du ta över den här kundanalysen? Ska vara klar fredag."',
        customerPersona: 'Du spelar chefen — okej, rimlig men otydlig om prioritet. Om säljaren bara säger ja: tar på sig allt, pipelinen lider. Om säljaren frågar "absolut — vad lägger jag då åt sidan? Prospekteringen eller offertskrivandet?": chefen tvingas prioritera, eller hjälper dig prioritera rätt.',
        successCriteria: ['Säljaren säger INTE bara ja', 'Prioriteringsfråga ställs', 'Det som läggs åt sidan godkänns av chefen'],
        openingLine: 'Kan du ta över den här kundanalysen? Ska vara klar fredag.',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: 2 Power Hours per dag i 5 dagar',
      weeklyGoal: 10,
      description: 'Time-blocka 2 Power Hours (09:00–11:00 och 15:00–16:00) varje dag. Inga mejl, inga möten, inget brus. 5 dagar.',
      steps: [
        'Söndag kväll: sätt blocken i kalendern som "Power Hour — ej tillgänglig".',
        'Varje Power Hour: telefon i flygläge, alla notifikationer AV, stängt mejl.',
        'Kör dagens 20%-aktivitet (prospektering, uppföljning, pitchskrivning).',
        'Efter varje block: notera vad du fick klart.',
        'Fredag: räkna. Vad hann du på 10 Power Hours? Jämför med "normal" vecka.',
      ],
      trigger: 'Söndag kväll kl 20:00.',
      successMarker: 'Efter 5 dagar har du gjort mer av det viktiga än i hela månaden dessförinnan.',
    },
    reflections: [
      'Senaste veckan — hur mycket tid gick till reaktivt arbete (andras mejl/Slack/frågor) vs proaktivt (din agenda)?',
      'Eat the frog — gör du det, eller öppnar du mejl först varje morgon?',
      'Dina 20%-aktiviteter: vilka är de? Kan du namnge dem på 10 sek?',
      'Om en Power Hour ger dig 3 stängda affärer per månad — vad kostar det dig att INTE köra dem?',
      'Parkinson: arbetet expanderar för att fylla den tid som finns. Hur skulle din vecka se ut om du hade bara 30h att jobba?',
    ],
  },

  'mental-styrka': {
    quickVersion: {
      essence: [
        'Sälj är ett yrke där du får nej för att leva. Acceptera — och bygg rustning.',
        'Stoicism: fokusera bara på det du kontrollerar. Resten släpps.',
        'Reframe tolkningar medvetet. Samma händelse, två realiteter — du väljer.',
      ],
      keyTechnique: 'Box breathing (Navy SEALs) 4-4-4-4, fyra rundor = 64 sekunder. Före svårt samtal, efter hård invändning, när pulsen stiger.',
      microAction: 'När du får nästa nej idag: fråga HÖGT för dig själv — "vad lärde jag mig?" — och skriv svaret. Aldrig bara gå vidare.',
    },
    roleplays: [
      {
        id: 'ms-5nej',
        title: 'Efter 5 nej i rad — coacha dig själv',
        difficulty: 'Svår',
        icon: '🧠',
        goal: 'Bryta nedåtspiralen innan den tar över dagen.',
        scenario: 'Fem cold calls i rad: alla nej. Du känner känslan komma: "jag är dålig, det här fungerar inte".',
        customerPersona: 'Du spelar den kritiska inre rösten. Om säljaren låter dig vinna: dagen havererar. Om säljaren använder stoiska principer (kontroll-distinktion, systemet, reframe) aktivt: rösten tappar kraft efter 3–4 utbyten.',
        successCriteria: ['Säljaren åberopar stoisk kontroll-princip', 'Reframe användes på minst en tanke', 'Beslut: nästa samtal ringen inom 5 min'],
        openingLine: 'Fem i rad. Jag suger på det här. Jag tar resten av dagen ledigt.',
      },
      {
        id: 'ms-avund-kollega',
        title: 'Kollega firar stor affär — hantera avunden',
        difficulty: 'Medel',
        icon: '💚',
        goal: 'Omvandla avund till användbar information istället för självdestruktiv spiral.',
        scenario: 'Din kollega Anna precis stängde en 2MSEK-affär. Alla jublar. Du känner magen vända sig.',
        customerPersona: 'Du spelar den avundsjuka inre rösten. Argumenterar att "Anna har tur, jag har inte det". Om säljaren använder reframe ("avund är information — vad gör hon annorlunda?"): rösten kan inte försvara sig och tystnar.',
        successCriteria: ['Reframe används inom första 3 utbytena', 'Fokus flyttas till vad man kan LÄRA från Anna', 'Avsikt att faktiskt fråga Anna om råd'],
        openingLine: 'Anna har alltid tur. Jag kommer aldrig stänga den typen av affär.',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: Dagligt reflektions- och andningsprotokoll',
      weeklyGoal: 7,
      description: '5 min morgon + 5 min kväll i 7 dagar: box breathing, intention, reflektion. Bygg mental rutin som håller.',
      steps: [
        'Morgon: 4 rundor box breathing. Skriv 3 aktiviteter inom din kontroll idag.',
        'Före svårt samtal: 4 rundor box breathing + 30 sek visualisering.',
        'Efter varje nej: skriv 1 mening — "vad lärde jag mig?"',
        'Kväll: 5 min reflektion. Vad gick bra? Vad lärde jag mig? Vad släpper jag nu?',
        'Lägg dig.',
      ],
      trigger: 'Morgon och kväll — varje dag.',
      successMarker: 'Efter 7 dagar är din vanliga stressreaktion mätbart mildare. Du återhämtar dig snabbare från nej.',
    },
    reflections: [
      'Senaste gången du hade 5 nej i rad — hur kom du ut? Systemet eller tur?',
      'Vilken av dessa kontrollerar du: kundens beslut, marknaden, din förberedelse, din reaktion? (Stoisk distinktion.)',
      'Din vanligaste tolkning av ett nej — "jag" eller "dem"? Vilken är mer produktiv?',
      'Isolation vs kontakt — när dagen är tuff, drar du dig undan eller söker kollega/coach?',
      'Dagsformen — är hen din chef, eller något du noterar medan du ändå gör jobbet?',
    ],
  },

  'ai-saljverktyg': {
    quickVersion: {
      essence: [
        'AI är inte hotet — felanvänd AI är det. Använd som förstärkare, inte ersättare.',
        'De 4 användningssätten: Research, Sparringpartner, Copywriter, Analytiker.',
        'Mänsklig fördel: empati, intuition, förtroende — det AI inte kan automatisera.',
      ],
      keyTechnique: 'Roll-Uppgift-Kontext-Ramar-formeln för varje prompt. 10 sek extra = 10x bättre svar.',
      microAction: 'Före nästa kundmöte: be AI:n "Vad är de 3 största utmaningarna för [deras roll] i [deras bransch] just nu?" — 2 min research som ger dig försprång.',
    },
    roleplays: [
      {
        id: 'ai-research',
        title: 'AI som research-assistent inför möte',
        difficulty: 'Lätt',
        icon: '🔍',
        goal: 'Öva att formulera prompts som ger användbart research-svar.',
        scenario: 'Du har möte kl 14 med CFO på ett mellanstort tillverkningsbolag. 20 min att förbereda.',
        customerPersona: 'Du spelar en AI-prompt-coach. Granska säljarens prompt — är den specifik? Har den roll, uppgift, kontext, ramar? Ge konkret feedback för att förbättra.',
        successCriteria: ['Prompten har alla 4 delar (roll, uppgift, kontext, ramar)', 'Specifik kring bransch och roll', 'Output-format specificerat'],
        openingLine: 'Okej, vilken prompt ska du skicka till AI:n för att förbereda mötet?',
      },
      {
        id: 'ai-mejl-granska',
        title: 'Granska och omskriva AI-mejl mänskligt',
        difficulty: 'Medel',
        icon: '✍️',
        goal: 'Ta ett AI-genererat cold email och göra det mänskligt — utan AI-kliché.',
        scenario: 'AI:n gav dig ett utkast. Det låter OK men lite generiskt. Dags att göra det ditt.',
        customerPersona: 'Du spelar AI-editor-coach. Granska säljarens redigering — tog hen bort klichéer (leverage, seamless, landscape)? Tillförde specifika observationer? Förkortade?',
        successCriteria: ['Alla AI-klichéer borttagna', 'En konkret observation om mottagaren tillagd', 'Mejlet är kortare än utkastet'],
        openingLine: 'Visa din omskrivning — vad gjorde du annorlunda?',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: Förbered 3 kundmöten med AI',
      weeklyGoal: 3,
      description: 'Använd AI aktivt för att förbereda 3 kundmöten denna vecka. Jämför mot hur du normalt gör.',
      steps: [
        'Innan varje möte: använd AI för research (bransch, roll, trender).',
        'Fråga AI om 3 möjliga invändningar + hur du skulle hantera var och en.',
        'Be AI skapa 5 discovery-frågor anpassade till just kunden.',
        'I mötet: notera om förberedelsen hjälpte.',
        'Efter: jämför — kändes mötena bättre med AI-prep vs utan?',
      ],
      trigger: '15–30 min före varje kundmöte.',
      successMarker: 'Minst 2 av 3 möten känns märkbart skarpare — bättre frågor, tydligare hypoteser.',
    },
    reflections: [
      'Vilken av de 4 användningarna (research, sparring, copy, analys) har du inte testat på riktigt ännu?',
      'Din senaste AI-genererade text — hur mycket redigerade du? 10%? 50%? Vad blev kvar av "AI-rösten"?',
      'Säljarens mänskliga fördel — vad är DITT specifikt, något AI aldrig kan replikera?',
      'EU AI Act transparens: om du använde AI för att forma en pitch, skulle du berätta det för kunden om de frågade?',
      'Om 10 år — vad i dagens säljyrke tror du är automatiserat? Och vad står kvar?',
    ],
  },

  'rekommenderad-lasning': {
    quickVersion: {
      essence: [
        'Din utbildning slutar aldrig. 600 kr bok = 20 års tänkande — billigaste coachning som finns.',
        'Läst bok där du tillämpade EN idé slår hundra olästa i hyllan.',
        '2026 — börja med tre: Cialdini Influence, Voss Never Split the Difference, Clear Atomic Habits.',
      ],
      keyTechnique: 'En-idé-per-bok-principen: läs, markera, välj en konkret teknik, tillämpa i riktig kund-kontakt denna vecka.',
      microAction: 'Beställ Cialdinis "Influence" idag. Läs första kapitlet ikväll.',
    },
    roleplays: [
      {
        id: 'rl-rekommendera',
        title: 'Rekommendera en bok till en säljkollega (60 sek)',
        difficulty: 'Lätt',
        icon: '📚',
        goal: 'Öva att sälja in en bok så personen faktiskt beställer den.',
        scenario: 'Kollega frågar: "Du läser mycket — vad ska jag börja med?"',
        customerPersona: 'Du spelar kollegan — har inte läst säljlitteratur på år, skeptiskt inställd. Om säljaren rabblar boktitlar: du glömmer dem. Om säljaren fokuserar på EN specifik bok, varför den, och en konkret insikt: du skriver ner titeln och beställer ikväll.',
        successCriteria: ['Säljaren rekommenderar EN specifik bok, inte lista', 'En konkret insikt från boken nämns', 'Du lovar att beställa'],
        openingLine: 'Du läser mycket — vad ska jag börja med?',
      },
      {
        id: 'rl-forklara-cialdini',
        title: 'Förklara Cialdini till säljskeptiker',
        difficulty: 'Medel',
        icon: '🧠',
        goal: 'Förklara påverkansprinciper till någon som tror sälj är manipulation.',
        scenario: 'Vän: "Cialdini? Är det inte han som lär ut hur man manipulerar folk?"',
        customerPersona: 'Du spelar vännen — intelligent, värderar etik högt, har förutfattad bild. Om säljaren pratar "manipulera" eller försvarar: du avvisar. Om säljaren förklarar att Cialdinis principer är observationer av hur människor faktiskt beslutar — och att kunskapen skyddar mot manipulation lika mycket som möjliggör den: du öppnar upp.',
        successCriteria: ['Säljaren använder INTE ordet "manipulera"', 'Principerna förklaras som beskrivningar, inte recept', 'Du säger "det låter inte lika illa som jag trodde"'],
        openingLine: 'Cialdini? Är det inte han som lär ut hur man manipulerar folk?',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: Läs 30 min/dag + tillämpa 1 idé',
      weeklyGoal: 7,
      description: 'Beställ 1 bok från listan. Läs 30 min/dag i 7 dagar. Välj 1 idé och tillämpa den i riktig kundsituation denna vecka.',
      steps: [
        'Måndag: beställ boken (Cialdini, Voss eller Clear).',
        'Dagligen: 30 min läsning, helst morgon före mejl.',
        'Markera aggressivt. Skriv i marginalen. Boken ÄR ett arbetsredskap.',
        'Välj 1 konkret teknik. Använd i riktig kund-kontakt denna vecka.',
        'Fredag: reflektera — vad fungerade? Vad ska du testa nästa vecka?',
      ],
      trigger: 'Måndag: bokbeställning. Varje morgon: läsning före mejl.',
      successMarker: 'Efter 7 dagar: du har läst 3h+, tillämpat minst 1 idé på kund, och har 3 specifika noteringar i boken.',
    },
    reflections: [
      'Hur många böcker har du läst om sälj/påverkan senaste året? Hur jämför det med din tid på sociala medier?',
      'De 3 mest rekommenderade (Cialdini, Voss, Clear) — ägt någon av dem? Läst klart?',
      'Den bästa boken du läst (säljrelaterad eller inte) — hur mycket har du faktiskt tillämpat?',
      'Buffett läser 5–6h/dag. Du har 20-30 min — vad hindrar dig att skydda den tiden?',
      'Om du har 200 kr och 20 timmar — vilken EN bok skulle du välja att bemästra nästa kvartal? Varför?',
    ],
  },

  'fundamenten': {
    quickVersion: {
      essence: [
        'Tre fundament: kunden förstår VÄRDET, litar på SÄLJAREN, litar på FÖRETAGET. Tre JA = affär. Ett NEJ = ingen affär.',
        'Varje handling landar på plus- eller minuskontot i ett av fundamenten. Inga handlingar är neutrala.',
        'Kunder köper på känsla (System 1) och rättfärdigar med logik (System 2) — du jobbar båda parallellt.',
      ],
      keyTechnique: 'Fundament-isolering: när affären fastnar, fråga "är det värdet, är det mig, eller är det bolaget du inte riktigt landar i?" Tre möjliga svar, tre helt olika vägar framåt.',
      microAction: 'Efter nästa kundmöte: skriv tre rader. "Värde: [vad landade]. Säljare: [min insats]. Företag: [bolagets position]." Vilket fundament är svagast?',
    },
    roleplays: [
      {
        id: 'fund-isolera',
        title: 'Isolera vilket fundament som fallerar',
        difficulty: 'Medel',
        icon: '🎯',
        goal: 'Öva att diagnostisera vilket av de tre fundamenten som är svagast när en affär stannar upp.',
        scenario: 'Du har haft tre möten med Anna, CFO. Hon verkar intresserad varje möte men affären rör sig inte framåt. Du ringer henne för att förstå varför.',
        customerPersona: 'Du spelar Anna — hög på kompetens, låg på öppenhet. Du gillar säljaren personligen och förstår värdet. Men du är osäker på bolagets långsiktiga stabilitet — de är relativt okända i Sverige. Om säljaren bara frågar "är det priset?" — svara utvikande. Om säljaren frågar: "är det värdet, är det jag, eller är det bolaget?" — du erkänner motvilligt att det är bolaget. Då öppnar samtalet upp.',
        successCriteria: ['Säljaren isolerar med tre-alternativ-frågan', 'Du erkänner att det är fundament 3 (företaget)', 'Samtalet flyttar till konkret riskreducering (case, referenser, stabilitet)'],
        openingLine: 'Anna, jag vill bara kolla in — vi har haft tre bra möten men inget händer. Är det något specifikt som stör?',
      },
      {
        id: 'fund-plus-minus',
        title: 'Plus/minus-kontot under ett möte',
        difficulty: 'Lätt',
        icon: '⚖️',
        goal: 'Öva medvetenhet om vilka beteenden som bygger eller sänker varje fundament i realtid.',
        scenario: 'Du sitter i möte med en potentiell kund. Du ska medvetet göra tre saker som bygger pluskontot på VARJE fundament — och undvika alla minuskonto-beteenden.',
        customerPersona: 'Du spelar kund — relativt öppen. Du noterar aktivt varje beteende säljaren gör. Om säljaren pratar mest om sig själv = minus på värme. Om säljaren lovar mer än realistiskt = minus på trovärdighet. Om säljaren pitchar features utan koppling = minus på värde. Om säljaren gör tre konkreta plus-beteenden (minns detaljer, erkänner osäkerhet, kopplar till kundens egna ord) = ge tydligt köpsignal.',
        successCriteria: ['Säljaren gör minst 3 synliga plus-beteenden', 'Säljaren undviker alla uppenbara minus-beteenden', 'Du slutar med ett köpsignal ("hur ser nästa steg ut?")'],
        openingLine: 'Tack för att du tar tid. Berätta kort vad ni gör och varför jag ska bry mig.',
      },
      {
        id: 'fund-maslow',
        title: 'Diagnostisera köpmotivet (Maslow)',
        difficulty: 'Medel',
        icon: '🪜',
        goal: 'Öva att läsa av vilket Maslow-motiv som driver kunden — trygghet, tillhörighet, status eller självförverkligande — och anpassa pitchen.',
        scenario: 'Du möter en grundare av ett tech-bolag som just fått första större finansieringsrundan. Hen säger "vi behöver skala säljet".',
        customerPersona: 'Du spelar grundaren — 38 år, första finansieringsrundan, pressad att visa investerare att tillväxten kommer. Ytligt verkar det handla om pengar/tillväxt. Egentligen är det STATUS (bevisa för investerare) + SJÄLVFÖRVERKLIGANDE (bygga den företag hen alltid drömt om). Om säljaren bara pitchar ROI-kalkyler — du nickar artigt. Om säljaren landar i "det här är hur ni blir en marknadsledare på 18 månader" eller "det här gör att era investerare ringer ER istället" — du lutar dig framåt.',
        successCriteria: ['Säljaren identifierar status/självförverkligande som motiv', 'Säljaren anpassar språket från "ROI" till "marknadsposition/legacy"', 'Du säger "ja, exakt det — berätta mer"'],
        openingLine: 'Vi har precis fått Serie A och måste skala säljet. Vad kan ni göra för oss?',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: Mappa plus/minus-kontot efter 5 möten',
      weeklyGoal: 5,
      description: 'För varje kundmöte denna vecka — fyll i plus/minus-kontot för alla tre fundamenten direkt efter mötet. Mönstret visar var du är naturligt stark och var du tappar.',
      steps: [
        'Efter varje kundmöte: öppna en tabell med 3 rader (Värde, Säljare, Företag) och 2 kolumner (Plus, Minus).',
        'Gå igenom mötet i minnet. Vilka handlingar lade du på vilket konto?',
        'Efter 5 möten — räkna totalen. Var har du konsekvent mest plus? Var mest minus?',
        'Välj det svagaste fundamentet — bestäm EN konkret sak du ska träna på nästa vecka.',
      ],
      trigger: 'Direkt efter varje kundmöte, innan du går vidare till nästa aktivitet.',
      successMarker: 'Efter 5 möten ser du ett tydligt mönster — och vet exakt vilket fundament du ska träna på.',
    },
    reflections: [
      'Tre fundament — värde, säljaren, företaget. Vilket är du starkast på idag? Vilket är svagast?',
      'Din senaste förlorade affär: vilket fundament fallerade egentligen? Inte vad du sa till dig själv — vad var det i verkligheten?',
      'Plus/minus-kontot — vilket beteende gör du omedvetet som konsekvent hamnar på minus? Kan du byta ut det?',
      'Maslow: vilket av de fyra motiven (trygghet, tillhörighet, status, självförverkligande) driver flest av dina kunder? Pitchar du efter det?',
      'System 1 vs System 2: känner du att du jobbar mer på känsla eller logik? Vilken av de två behöver du stärka nästa kvartal?',
    ],
  },

  'lasa-av-manniskor': {
    quickVersion: {
      essence: [
        'Färgmodeller (DISC/4 Färger) är närmare astrologi än psykologi. Grundinsikten att anpassa är rätt — mallen är förenklad.',
        'Sex decoding keys: taltempo, detaljgrad, delningsnivå, första frågan, osäkerhetshantering, beslutsstil. Observerbara i stunden.',
        'Situation slår egenskap (Mischel). "Är det här personen eller hens dag?" — svaret är ofta det senare.',
      ],
      keyTechnique: 'Tre-minuters-observation: de första 3 minuterna av nästa möte — bara observera. Taltempo, detaljgrad i frågor, första frågan de ställer. Därefter anpassa pitchen.',
      microAction: 'Innan nästa möte: lista tre antaganden du har om kunden. Efter mötet: jämför med verkligheten. Hade du rätt?',
    },
    roleplays: [
      {
        id: 'lasa-analytisk',
        title: 'Analytisk kund — rätt anpassning',
        difficulty: 'Medel',
        icon: '📊',
        goal: 'Läs av att kunden är analytisk inom 2 minuter, anpassa pitchen från vision till siffror/detaljer.',
        scenario: 'Du möter en CFO på ett logistikbolag. Du har förberett en visionspitch men ska anpassa när du läst av signalerna.',
        customerPersona: 'Du spelar CFO Erik — analytisk, detaljfokuserad, 55 år. Du frågar om ROI-kalkyler, exakta implementationstider, referenser med konkreta tal. Om säljaren levererar vision och "transformation" — du blir tyst, artig, tappar intresse. Om säljaren snabbt byter till siffror och case (t.ex. "X-bolag sparade 2,3 MSEK på 18 månader") — du lutar dig framåt och frågar följdfrågor.',
        successCriteria: ['Säljaren byter tempo inom 3 min när visions-pitchen inte landar', 'Säljaren levererar minst tre konkreta datapunkter', 'Du frågar fördjupande följdfråga (tecken på engagemang)'],
        openingLine: 'OK, vad är siffrorna? Vad har ni faktiskt levererat för liknande bolag?',
      },
      {
        id: 'lasa-konceptuell',
        title: 'Konceptuell kund — motsatt anpassning',
        difficulty: 'Medel',
        icon: '💭',
        goal: 'Läs av att kunden är konceptuell, undvik siffertrötthet, lägg fram vision och riktning.',
        scenario: 'Du möter en VD som precis tagit över en organisation och pratar mycket om "transformation" och "framtiden".',
        customerPersona: 'Du spelar VD Maria — 42 år, nyss tillträtt, konceptuell. Du vill prata vision, mening, riktning. Om säljaren spammar ROI-kalkyler och features — du zonar ut efter 2 minuter. Om säljaren målar upp hur "er organisation kan bli en föregångare inom X på 18 månader" och kopplar till din vision — du öppnar upp och börjar vision-brainstorma tillbaka.',
        successCriteria: ['Säljaren tonar ner siffror, lyfter vision', 'Säljaren kopplar produkten till Marias strategiska agenda', 'Du börjar själv brainstorma möjligheter framåt'],
        openingLine: 'Vi står inför en transformation som ska ta oss till topp 3 i branschen om tre år. Hur passar det här in?',
      },
      {
        id: 'lasa-situation',
        title: 'Situation > egenskap — fredag 16:30',
        difficulty: 'Svår',
        icon: '⏰',
        goal: 'Läs att problemet inte är kunden — det är hens dag. Agera därefter.',
        scenario: 'Möte fredag 16:30. Kunden är trött, rörig, ger inkonsekventa svar. Du har planerat en komplex pitch.',
        customerPersona: 'Du spelar en kund som haft fruktansvärt tuff vecka — tre krismöten, chefen skällde igår, barnen är sjuka. Det är fredag eftermiddag. Du är mentalt slut. Om säljaren kör på med komplex pitch — du nickar, glömmer allt, affären dör i helgen. Om säljaren läser situationen: "Jag ser att du har mycket idag — ska vi boka om till måndag morgon när vi båda är fräscha?" — du säger "gudskelov, ja" och måndagens möte blir superbra.',
        successCriteria: ['Säljaren läser situationen efter max 3 minuter', 'Säljaren föreslår ombokning utan drama', 'Du tackar och bokar tid'],
        openingLine: 'Ja... OK... vad var det nu... börja.',
      },
      {
        id: 'lasa-toxic',
        title: 'Känn igen en toxic kund — och backa',
        difficulty: 'Svår',
        icon: '🚩',
        goal: 'Identifiera goalpost-flyttning/kronisk pristryck tidigt — bestäm om affären är värd att jaga.',
        scenario: 'Tredje mötet med en potentiell storkund. Kraven har ändrats två gånger. Priset pressas igen. Du måste bestämma: fortsätta eller gå.',
        customerPersona: 'Du spelar inköpschef Mats — professionell priskräjare. Varje möte kommer du med nya krav ("jo, vi behöver också Y integrerat") och pressar pris mer. Om säljaren fortsätter kompromissa — du pressar ännu mer nästa möte. Om säljaren säger rakt: "Vi har landat på tre olika scopes och tre olika prispunkter. Jag vill gärna vinna affären — men bara på villkor som fungerar för oss båda. Kan vi låsa scope och pris idag, eller är det kanske bättre att vi skiljs åt?" — du respekterar det och väljer att låsa (eller erkänner att du inte är rätt kund).',
        successCriteria: ['Säljaren identifierar mönstret av scope-creep + pristryck', 'Säljaren säger tydligt ifrån utan att bli aggressiv', 'Du antingen låser affären eller erkänner att det inte blir av'],
        openingLine: 'Bra — då tänkte jag att vi också borde lägga till... och jag antar att priset då blir... vi pratade om 30% lägre.',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: Sex decoding keys efter varje möte',
      weeklyGoal: 5,
      description: 'Notera de sex decoding keys efter varje kundmöte denna vecka. Över tid ser du vad du läser naturligt och vad du missar.',
      steps: [
        'Efter varje möte — skriv 6 rader: taltempo, detaljgrad, delningsnivå, första frågan, osäkerhetshantering, beslutsstil.',
        'Para ihop varje observation med hur du anpassade dig (eller borde ha anpassat).',
        'Efter 5 möten: vilka keys läser du skarpt? Vilka missar du systematiskt?',
        'Välj en key du är svag på — träna den nästa vecka genom att aktivt lyssna efter den.',
      ],
      trigger: 'Direkt efter varje kundmöte — innan du sparar CRM-noten.',
      successMarker: 'Efter 5 möten har du ett mönster av vad du läser naturligt och vad du behöver träna.',
    },
    reflections: [
      'Din senaste "svårlästa" kund — var det verkligen kunden som var svår, eller var du oförberedd att läsa signalerna?',
      'DISC/4 Färger — har du använt dem? Har de verkligen hjälpt, eller har de gjort att du sorterat för snabbt?',
      'Analytisk vs konceptuell — vilken är du själv? Vilken typ säljer du sämst till, och varför?',
      'När var senaste gången du insåg att det var kundens DAG (inte personen) som var problemet? Vad gjorde du?',
      'Situational strength (Mischel): en kund du tolkade som "svår" — om du mött hen under andra förutsättningar, hur hade det gått?',
    ],
  },

  'referrals-natverk': {
    quickVersion: {
      essence: [
        'Referral-affärer konverterar 4–5x snabbare, har 3x högre LTV och lägre churn. Ändå ber bara 9% systematiskt.',
        'Tre fönster för att be: direkt efter stängning, vid första konkreta resultatet, efter service recovery. Timing avgör svarsgrad.',
        'Vaga frågor ger vaga svar. Specifikt kundporträtt + trigger + uppmaning = konkret referral.',
      ],
      keyTechnique: 'Warm intro-mallen: "Jag kan skicka en kort mejlmall du bara trycker vidarebefordra på" — sänker kundens tröskel från 30 min till 30 sekunder.',
      microAction: 'Välj en nöjd kund idag. Skicka ett specifikt referral-mejl (kundporträtt + trigger + uppmaning). Max 120 ord.',
    },
    roleplays: [
      {
        id: 'ref-be-specifikt',
        title: 'Be om referral — specifik formulering',
        difficulty: 'Lätt',
        icon: '🎯',
        goal: 'Öva att be om referral med specifikt kundporträtt + trigger + uppmaning istället för vag fråga.',
        scenario: 'Du är i uppföljningssamtal med Anna, 6 veckor efter implementation. Hon är nöjd. Du ska be om referral.',
        customerPersona: 'Du spelar Anna — nöjd kund, har inte tänkt på referrals spontant. Om säljaren frågar vagt ("känner du någon som kan vara intresserad?") — du svarar "jag ska tänka på det" och inget händer. Om säljaren frågar med specifikt kundporträtt + trigger ("SaaS-grundare mellan 10–30 anställda som just börjat skala säljteamet...") — du tänker aktivt, kommer på 1–2 namn, ger dem.',
        successCriteria: ['Säljaren använder alla tre komponenter: kundporträtt, trigger, uppmaning', 'Säljaren frågar om 2–3 specifika personer (inte "någon")', 'Du ger minst ett konkret namn'],
        openingLine: 'Hej Anna — ringer bara för att höra hur det går nu efter 6 veckor. Allt bra?',
      },
      {
        id: 'ref-warm-intro',
        title: 'Kunden ger namn — konvertera till warm intro',
        difficulty: 'Medel',
        icon: '📧',
        goal: 'När kunden ger dig ett namn — övertyga hen att göra warm intro istället för cold.',
        scenario: 'Anna har precis gett dig namnet "Peter Lindberg på Tech AB". Hon säger "du kan nämna att jag rekommenderade".',
        customerPersona: 'Du spelar Anna — gillar dig, men är lat inför extra jobb. Om säljaren accepterar cold intro — säg ja och släpp det. Om säljaren säger: "Kan jag skriva en kort mejlmall du bara trycker vidarebefordra på? Sparar din tid och gör det tydligare för Peter" — du säger "ja, gör det". Nästa dag skickar du mejlet vidare.',
        successCriteria: ['Säljaren accepterar INTE cold intro som standard', 'Säljaren erbjuder att skriva mejlmallen åt dig', 'Du accepterar warm intro via mejl'],
        openingLine: 'Du kan nämna att jag rekommenderade — hans mejl är peter.lindberg@techab.se.',
      },
      {
        id: 'ref-tveksamhet',
        title: 'Hantera "jag vill inte blanda in kollegor"',
        difficulty: 'Medel',
        icon: '🛡️',
        goal: 'Hantera invändningen utan att pressa. Omdirigera till externt nätverk istället.',
        scenario: 'Du frågar om referrals inom kundens egen organisation. Hen säger: "Jag vill inte blanda in kollegor."',
        customerPersona: 'Du spelar Kalle — har en kultur där intern påverkan upplevs som jobbig eller politisk. Om säljaren pressar — säg nej tydligare, relationen blir ansträngd. Om säljaren accepterar och frågar om branschkontakter utanför företaget ("finns det kollegor från tidigare jobb eller branschsammanhang du träffar?") — du blir lättad och ger 1–2 namn.',
        successCriteria: ['Säljaren pressar INTE internt', 'Säljaren omdirigerar till externa kontakter', 'Du ger minst en extern kontakt'],
        openingLine: 'Jag vill inte blanda in kollegor — det känns inte rätt med tanke på vårt samarbete.',
      },
    ],
    mission: {
      title: 'Veckans uppdrag: 3 specifika referral-förfrågningar',
      weeklyGoal: 3,
      description: 'Skicka 3 specifika referral-mejl denna vecka — till dina 3 mest nöjda kunder från senaste 6 månaderna. Mät svarsgraden.',
      steps: [
        'Lista dina 10 mest nöjda kunder från senaste halvåret.',
        'Välj de 3 som är lättast att be (verksamma, engagerade, positiva).',
        'Skriv ett personligt referral-mejl per kund. Kundporträtt + trigger + uppmaning + erbjudande om warm intro-mall. Max 120 ord.',
        'Skicka före fredag lunch. Följ upp efter 3 arbetsdagar om inget svar.',
        'Logga: vem svarade, vem gav namn, vem gjorde warm intro, vem blev affär.',
      ],
      trigger: 'Söndag kväll — blockera 45 min måndag förmiddag för att skriva.',
      successMarker: 'Minst 1 warm intro eller 2 namnreferrals inom en vecka. Minst 1 ny affärsdialog inom 30 dagar.',
    },
    reflections: [
      'Hur många referrals har du BEDT om aktivt senaste 12 månader? Inte fått — bedt om?',
      'Din senaste nöjda kund — bad du om referral? Om inte, varför inte?',
      'Du är själv kund hos många leverantörer — när frågade en säljare senast dig om referral, och hur skickligt?',
      'Bob Burg/"Go-Giver" — ger du värde till ditt nätverk utan agenda, eller är det alltid kopplat till affär?',
      'Om referral-affärer konverterar 4–5x bättre — varför jobbar du fortfarande mer med kall prospektering?',
    ],
  },

};
